# Generated by Django 3.1.7 on 2021-03-20 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
